[graph]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
# Ignore unmaintained crates for now - `paste` used by `utoipa_axum` is unmaintained and I
# can't seem to get the ignored field to work without the crate being yanked.
# For the `utoipa` issue, see <https://github.com/juhaku/utoipa/issues/1336>
unmaintained = "none"

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Unicode-3.0",
  "ISC",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "AGPL-3.0",
  "CDLA-Permissive-2.0",
  "Zlib",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
