services:
  db:
    image: postgres:16.0
    container_name: curto-db
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - curto-db:/var/lib/postgresql/data

volumes:
  curto-db:
    driver: local
