[advisories]
ignore = [
  # From `sqlx-mysql`, which is not actually used here. See <https://github.com/launchbadge/sqlx/issues/3211>. 
  "RUSTSEC-2023-0071",
]
severity_threshold = "low"

[output]
format = "terminal" # "terminal" (human readable report) or "json"
quiet = false       # Only print information on error
show_tree = true    # Show inverse dependency trees along with advisories (default: true)

[yanked]
enabled = true      # Warn for yanked crates in Cargo.lock (default: true)
update_index = true # Auto-update the crates.io index (default: true)
