name: Audit dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
      branches: ["main"]
  pull_request:
      branches: ["main"]
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit
        run: |
          cargo install --locked cargo-audit && cargo audit

      - name: Deny
        run: |
          cargo install --locked cargo-deny && cargo deny check
